### PR TITLE
TailWind CSS added

### PR DESCRIPTION
**Pull request by AnshulGoyal589**
Till now only login and signup pages are accessible, so i have added tailwind CSS in them and also improved navbar CSS.
Closes issue #1

### CODE REVIEW

**Comment by AnshulGoyal589** [comment]
@AnushkJain2201  can you please put it under hactoberfest label

**Comment by AnushkJain2201** [comment]
@AnshulGoyal589 Added the label

**Comment by AnushkJain2201** [comment]
@AnshulGoyal589 I believe now you are able to view this contribution in you hactoberfest account

**Comment by AnshulGoyal589** [comment]
tailwind css


Still it is showing this that it is not not hactoberfest 2023 label

**Comment by AnushkJain2201** [comment]
Wait

**Comment by AnushkJain2201** [comment]
What about now?

**Comment by AnshulGoyal589** [comment]
tailwind css 2
  
 ig now it is resolved, Thanks!

**Comment by AnushkJain2201** [comment]
No problem bro, keep contributing 🙌

**Pull request merged**
